services:
  asspp:
    image: ghcr.io/lakr233/assppweb:latest
    ports:
      - "8080:8080"
    volumes:
      - ./mnt/asspp-data:/data
    environment:
      - DATA_DIR=/data
      - PORT=8080
      # - DOWNLOAD_THREADS=8
      # - ACCESS_PASSWORD=your_password_here
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "5"
